'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';
import { Language } from '@/lib/types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.history': 'Optimization History',
    'hero.title': 'Resume Tailor',
    'hero.subtitle': 'AI Resume Tailor',
    'hero.description': 'AI-Powered Resume Optimization for Every Job',
    'hero.getStarted': 'Get Started',
    'features.title': 'How It Works',
    'features.upload': 'Upload your master resume',
    'features.paste': 'Paste target job description',
    'features.optimize': 'AI optimizes your resume',
    'features.download': 'Download tailored resume',
    'features.section': 'Features',
    'features.aiOptimization': 'AI-Powered Optimization',
    'features.aiOptimizationDesc': 'Smart content tailoring using advanced AI algorithms',
    'features.multiLanguage': 'Multi-Language Support',
    'features.multiLanguageDesc': 'Supports English, Chinese, Korean, Japanese, French, German',
    'features.instantResults': 'Instant Results',
    'features.instantResultsDesc': 'Get your optimized resume in 1-2 minutes',
    'testimonials.title': 'What Our Users Say',
    'faq.title': 'Frequently Asked Questions',
    'dashboard.welcome': 'Welcome',
    'dashboard.subtitle': 'AI optimized resume based on real data',
    'dashboard.uploadResume': 'Upload Your Resume',
    'dashboard.uploadDesc': 'parseResumeStructure',
    'dashboard.jobAnalysis': 'jobAnalysis',
    'dashboard.jobAnalysisDesc': 'match JobRequirements',
    'dashboard.aiOptimization': 'AI Resume Optimization',
    'dashboard.aiOptimizationDesc': 'intelligentOptimization',
    'dashboard.downloadResume': 'Download Resume',
    'dashboard.downloadDesc': 'getOptimizedResults',
    'upload.title': 'Upload Resume',
    'upload.description': 'Upload your resume, AI will intelligently parse and optimize for target positions',
    'upload.dragDrop': 'Drag & drop resume file here or click to upload',
    'upload.formats': 'Supported formats: PDF, DOC, DOCX (max 10MB)',
    'upload.selectFile': 'Select File',
    'upload.tips': 'Upload Tips:',
    'upload.tip1': 'Ensure resume structure is clear with complete personal information, work experience and skills',
    'upload.tip2': 'File content should be selectable text (not image format)',
    'upload.tip3': 'Supports Chinese and English resumes, AI will automatically detect language',
    'upload.tip4': 'If PDF cannot be parsed correctly, recommend converting to Word format or plain text',
    'results.title': 'Optimization Complete - Your Professional Resume',
    'results.subtitle': 'AI has successfully optimized your resume with significantly improved match rate!',
    'results.matchRate': 'Job Match Rate',
    'results.improvements': 'Improvement Items',
    'results.keywordMatches': 'Keyword Matches',
    'results.keywordAnalysis': 'Keyword Analysis Report',
    'results.matchedKeywords': 'Matched Keywords',
    'results.addedKeywords': 'Added Keywords',
    'results.suggestions': 'Optimization Suggestions',
    'results.optimizationImprovements': 'This Optimization Improvements',
    'results.resumePreview': 'Resume Preview',
    'results.downloadPDF': 'Download PDF',
    'results.downloadWord': 'Download Word',
    'results.printResume': 'Print Resume',
    'results.createNew': 'Create New Optimized Resume',
    'results.successMessage': 'Optimization Successfully Completed!',
    'results.successDesc': 'Your resume has been deeply optimized for the target position, expected interview invitation rate increased by 65%',
    'footer.copyright': '© 2024 Resume Tailor. AI-powered resume optimization for the modern job seeker.',
  },
  zh: {
    'nav.home': '首页',
    'nav.dashboard': '控制台',
    'nav.history': '优化历史',
    'hero.title': '简历裁缝',
    'hero.subtitle': 'AI 简历裁缝',
    'hero.description': '为每个职位提供AI驱动的简历优化',
    'hero.getStarted': '开始使用',
    'features.title': '工作流程',
    'features.upload': '上传您的主简历',
    'features.paste': '粘贴目标职位描述',
    'features.optimize': 'AI优化您的简历',
    'features.download': '下载定制简历',
    'features.section': '功能特色',
    'features.aiOptimization': 'AI智能优化',
    'features.aiOptimizationDesc': '使用先进AI算法智能剪裁内容',
    'features.multiLanguage': '多语言支持',
    'features.multiLanguageDesc': '支持中文、英文、韩文、日文、法文、德文',
    'features.instantResults': '即时结果',
    'features.instantResultsDesc': '1-2分钟内获得优化简历',
    'testimonials.title': '用户评价',
    'faq.title': '常见问题',
    'dashboard.welcome': '欢迎',
    'dashboard.subtitle': '基于真实数据的AI优化简历',
    'dashboard.uploadResume': '上传简历',
    'dashboard.uploadDesc': '解析简历结构',
    'dashboard.jobAnalysis': '职位分析',
    'dashboard.jobAnalysisDesc': '匹配职位要求',
    'dashboard.aiOptimization': 'AI简历优化',
    'dashboard.aiOptimizationDesc': '智能优化',
    'dashboard.downloadResume': '下载简历',
    'dashboard.downloadDesc': '获得优化结果',
    'upload.title': '上传简历',
    'upload.description': '上传您的简历，AI将智能解析并为目标职位优化',
    'upload.dragDrop': '拖拽简历文件到这里或点击上传',
    'upload.formats': '支持格式：PDF、DOC、DOCX（最大10MB）',
    'upload.selectFile': '选择文件',
    'upload.tips': '上传提示：',
    'upload.tip1': '确保简历结构清晰，包含完整的个人信息、工作经历和技能',
    'upload.tip2': '文件内容应为可选择文本（非图片格式）',
    'upload.tip3': '支持中英文简历，AI将自动检测语言',
    'upload.tip4': '如PDF无法正确解析，建议转换为Word格式或纯文本',
    'results.title': '优化完成 - 您的专业简历',
    'results.subtitle': 'AI已成功优化您的简历，匹配率显著提升！',
    'results.matchRate': '职位匹配率',
    'results.improvements': '改进项目',
    'results.keywordMatches': '关键词匹配',
    'results.keywordAnalysis': '关键词分析报告',
    'results.matchedKeywords': '匹配关键词',
    'results.addedKeywords': '添加关键词',
    'results.suggestions': '优化建议',
    'results.optimizationImprovements': '本次优化改进',
    'results.resumePreview': '简历预览',
    'results.downloadPDF': '下载PDF',
    'results.downloadWord': '下载Word',
    'results.printResume': '打印简历',
    'results.createNew': '创建新的优化简历',
    'results.successMessage': '优化成功完成！',
    'results.successDesc': '您的简历已针对目标职位进行深度优化，预计面试邀请率提升65%',
    'footer.copyright': '© 2024 简历裁缝。为现代求职者提供AI驱动的简历优化服务。',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.dashboard': 'ダッシュボード',
    'nav.history': '最適化履歴',
    'hero.title': 'Resume Tailor',
    'hero.subtitle': 'AI履歴書テーラー',
    'hero.description': 'すべての求人に対応するAI駆動の履歴書最適化',
    'hero.getStarted': '始める',
    'features.title': '使い方',
    'features.upload': 'マスター履歴書をアップロード',
    'features.paste': 'ターゲット求人情報を貼り付け',
    'features.optimize': 'AIが履歴書を最適化',
    'features.download': 'カスタマイズされた履歴書をダウンロード',
    'features.section': '機能',
    'features.aiOptimization': 'AI最適化',
    'features.aiOptimizationDesc': '高度なAIアルゴリズムによるスマートコンテンツ調整',
    'features.multiLanguage': '多言語サポート',
    'features.multiLanguageDesc': '英語、中国語、韓国語、日本語、フランス語、ドイツ語をサポート',
    'features.instantResults': '即座の結果',
    'features.instantResultsDesc': '1-2分で最適化された履歴書を取得',
    'testimonials.title': 'ユーザーの声',
    'faq.title': 'よくある質問',
    'dashboard.welcome': 'ようこそ',
    'dashboard.subtitle': '実データに基づくAI最適化履歴書',
    'dashboard.uploadResume': '履歴書アップロード',
    'dashboard.uploadDesc': '履歴書構造の解析',
    'dashboard.jobAnalysis': '求人分析',
    'dashboard.jobAnalysisDesc': '求人要件のマッチング',
    'dashboard.aiOptimization': 'AI履歴書最適化',
    'dashboard.aiOptimizationDesc': 'インテリジェント最適化',
    'dashboard.downloadResume': '履歴書ダウンロード',
    'dashboard.downloadDesc': '最適化結果の取得',
    'footer.copyright': '© 2024 Resume Tailor。現代の求職者のためのAI駆動履歴書最適化。',
  },
  ko: {
    'nav.home': '홈',
    'nav.dashboard': '대시보드',
    'nav.history': '최적화 기록',
    'hero.title': 'Resume Tailor',
    'hero.subtitle': 'AI 이력서 재단사',
    'hero.description': '모든 채용공고를 위한 AI 기반 이력서 최적화',
    'hero.getStarted': '시작하기',
    'features.title': '사용 방법',
    'features.upload': '마스터 이력서 업로드',
    'features.paste': '타겟 채용공고 붙여넣기',
    'features.optimize': 'AI가 이력서 최적화',
    'features.download': '맞춤형 이력서 다운로드',
    'features.section': '기능',
    'features.aiOptimization': 'AI 최적화',
    'features.aiOptimizationDesc': '고급 AI 알고리즘을 사용한 스마트 콘텐츠 조정',
    'features.multiLanguage': '다국어 지원',
    'features.multiLanguageDesc': '영어, 중국어, 한국어, 일본어, 프랑스어, 독일어 지원',
    'features.instantResults': '즉시 결과',
    'features.instantResultsDesc': '1-2분 내에 최적화된 이력서 확보',
    'testimonials.title': '사용자 후기',
    'faq.title': '자주 묻는 질문',
    'dashboard.welcome': '환영합니다',
    'dashboard.subtitle': '실제 데이터 기반 AI 최적화 이력서',
    'dashboard.uploadResume': '이력서 업로드',
    'dashboard.uploadDesc': '이력서 구조 분석',
    'dashboard.jobAnalysis': '채용공고 분석',
    'dashboard.jobAnalysisDesc': '채용 요구사항 매칭',
    'dashboard.aiOptimization': 'AI 이력서 최적화',
    'dashboard.aiOptimizationDesc': '지능형 최적화',
    'dashboard.downloadResume': '이력서 다운로드',
    'dashboard.downloadDesc': '최적화 결과 획득',
    'footer.copyright': '© 2024 Resume Tailor. 현대 구직자를 위한 AI 기반 이력서 최적화.',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.dashboard': 'Dashboard',
    'nav.history': 'Optimierungshistorie',
    'hero.title': 'Resume Tailor',
    'hero.subtitle': 'KI-Lebenslauf-Schneider',
    'hero.description': 'KI-gestützte Lebenslauf-Optimierung für jeden Job',
    'hero.getStarted': 'Loslegen',
    'features.title': 'So funktioniert es',
    'features.upload': 'Master-Lebenslauf hochladen',
    'features.paste': 'Ziel-Stellenbeschreibung einfügen',
    'features.optimize': 'KI optimiert Ihren Lebenslauf',
    'features.download': 'Maßgeschneiderten Lebenslauf herunterladen',
    'features.section': 'Funktionen',
    'features.aiOptimization': 'KI-Optimierung',
    'features.aiOptimizationDesc': 'Intelligente Inhaltsanpassung mit fortschrittlichen KI-Algorithmen',
    'features.multiLanguage': 'Mehrsprachige Unterstützung',
    'features.multiLanguageDesc': 'Unterstützt Englisch, Chinesisch, Koreanisch, Japanisch, Französisch, Deutsch',
    'features.instantResults': 'Sofortige Ergebnisse',
    'features.instantResultsDesc': 'Erhalten Sie Ihren optimierten Lebenslauf in 1-2 Minuten',
    'testimonials.title': 'Was unsere Nutzer sagen',
    'faq.title': 'Häufig gestellte Fragen',
    'dashboard.welcome': 'Willkommen',
    'dashboard.subtitle': 'KI-optimierter Lebenslauf basierend auf echten Daten',
    'dashboard.uploadResume': 'Lebenslauf hochladen',
    'dashboard.uploadDesc': 'Lebenslauf-Struktur analysieren',
    'dashboard.jobAnalysis': 'Stellenanalyse',
    'dashboard.jobAnalysisDesc': 'Stellenanforderungen abgleichen',
    'dashboard.aiOptimization': 'KI-Lebenslauf-Optimierung',
    'dashboard.aiOptimizationDesc': 'Intelligente Optimierung',
    'dashboard.downloadResume': 'Lebenslauf herunterladen',
    'dashboard.downloadDesc': 'Optimierte Ergebnisse erhalten',
    'footer.copyright': '© 2024 Resume Tailor. KI-gestützte Lebenslauf-Optimierung für moderne Jobsuchende.',
  },
  it: {
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.history': 'Cronologia Ottimizzazioni',
    'hero.title': 'Resume Tailor',
    'hero.subtitle': 'Sarto di CV AI',
    'hero.description': 'Ottimizzazione CV basata su AI per ogni lavoro',
    'hero.getStarted': 'Inizia',
    'features.title': 'Come Funziona',
    'features.upload': 'Carica il tuo CV principale',
    'features.paste': 'Incolla la descrizione del lavoro target',
    'features.optimize': 'AI ottimizza il tuo CV',
    'features.download': 'Scarica CV personalizzato',
    'features.section': 'Caratteristiche',
    'features.aiOptimization': 'Ottimizzazione AI',
    'features.aiOptimizationDesc': 'Adattamento intelligente dei contenuti usando algoritmi AI avanzati',
    'features.multiLanguage': 'Supporto Multi-Lingua',
    'features.multiLanguageDesc': 'Supporta Inglese, Cinese, Coreano, Giapponese, Francese, Tedesco',
    'features.instantResults': 'Risultati Istantanei',
    'features.instantResultsDesc': 'Ottieni il tuo CV ottimizzato in 1-2 minuti',
    'testimonials.title': 'Cosa Dicono i Nostri Utenti',
    'faq.title': 'Domande Frequenti',
    'dashboard.welcome': 'Benvenuto',
    'dashboard.subtitle': 'CV ottimizzato con AI basato su dati reali',
    'dashboard.uploadResume': 'Carica CV',
    'dashboard.uploadDesc': 'Analizza struttura CV',
    'dashboard.jobAnalysis': 'Analisi Lavoro',
    'dashboard.jobAnalysisDesc': 'Confronta requisiti lavoro',
    'dashboard.aiOptimization': 'Ottimizzazione CV AI',
    'dashboard.aiOptimizationDesc': 'Ottimizzazione intelligente',
    'dashboard.downloadResume': 'Scarica CV',
    'dashboard.downloadDesc': 'Ottieni risultati ottimizzati',
    'footer.copyright': '© 2024 Resume Tailor. Ottimizzazione CV basata su AI per il cercatore di lavoro moderno.',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.dashboard': 'Panel',
    'nav.history': 'Historial de Optimización',
    'hero.title': 'Resume Tailor',
    'hero.subtitle': 'Sastre de CV con IA',
    'hero.description': 'Optimización de CV impulsada por IA para cada trabajo',
    'hero.getStarted': 'Comenzar',
    'features.title': 'Cómo Funciona',
    'features.upload': 'Sube tu CV maestro',
    'features.paste': 'Pega la descripción del trabajo objetivo',
    'features.optimize': 'IA optimiza tu CV',
    'features.download': 'Descarga CV personalizado',
    'features.section': 'Características',
    'features.aiOptimization': 'Optimización IA',
    'features.aiOptimizationDesc': 'Adaptación inteligente de contenido usando algoritmos IA avanzados',
    'features.multiLanguage': 'Soporte Multi-Idioma',
    'features.multiLanguageDesc': 'Soporta Inglés, Chino, Coreano, Japonés, Francés, Alemán',
    'features.instantResults': 'Resultados Instantáneos',
    'features.instantResultsDesc': 'Obtén tu CV optimizado en 1-2 minutos',
    'testimonials.title': 'Qué Dicen Nuestros Usuarios',
    'faq.title': 'Preguntas Frecuentes',
    'dashboard.welcome': 'Bienvenido',
    'dashboard.subtitle': 'CV optimizado con IA basado en datos reales',
    'dashboard.uploadResume': 'Subir CV',
    'dashboard.uploadDesc': 'Analizar estructura CV',
    'dashboard.jobAnalysis': 'Análisis Trabajo',
    'dashboard.jobAnalysisDesc': 'Coincidir requisitos trabajo',
    'dashboard.aiOptimization': 'Optimización CV IA',
    'dashboard.aiOptimizationDesc': 'Optimización inteligente',
    'dashboard.downloadResume': 'Descargar CV',
    'dashboard.downloadDesc': 'Obtener resultados optimizados',
    'footer.copyright': '© 2024 Resume Tailor. Optimización de CV impulsada por IA para el buscador de empleo moderno.',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }): JSX.Element {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('resume-tailor-language') as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('resume-tailor-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}